### PR TITLE
fixes #59 - PDT Formatter: One-line shell-style comments converted to

### LINKED ISSUE #59: PDT Formatter: One-line shell-style comments converted to one-line C++-style comments
**Describe the bug**
Upon using the code formatter, one-line shell-style comments such as `# This is a one-line shell-style comment` are converted to `// This is a one-line shell-style comment` (one-line C++-style comments).

Since we're using the `#` and `//` comment types for slightly different uses, it is somewhat annoying.

**Describe the eclipse environment**
 - IDE: MyEclipse Enterprise Workbench version 2020.5.18, based on Eclipse Platform version 4.15.0.v20200305-0155.
 - PDT: Eclipse PDT version 7.1.0.202002212050.

**Describe your system**
 - OS: Windows 10
 - Version 1909 (build 18363.836)

**To Reproduce**
1. Open a PHP file having a one-line shell-style comment such as `# This is a one-line shell-style comment`
2. Right-click on the document
3. Click Source > Format
4. The document's one-line shell-style comments are converted to one-line C++-style comments such as `// This is a one-line shell-style comment` 

**Expected behavior**
The comment type should not change. Upon reformatting, the `#` comment token should remain `#`.

### PR DESCRIPTION
**Pull request by tbl0605**
one-line C++-style comments

Signed-off-by: tbl0605 <tbl0605@gmail.com>

### CODE REVIEW

**Comment by zulus** [comment]
Looks like your github mail not match with eclipse db ;)

**Comment by tbl0605** [comment]
> 
> 
> Looks like your github mail not match with eclipse db ;)

what a mess here, I used a different email address for all my previous PDT developments, but I added the tbl0605 github username to my eclipse account (which is linked to another email address). 
Previously, commiting patches through gerrit did always the correct "translation" between my gerrit account and my github account (all my patches are correctly labeled as "tbl0605").
If I don't add any "Signed-off-by" annotation, it should be ok no?

**Comment by zulus** [comment]
You are committer so sined off is not necessarry. Important is email you have in commit. So just amend with different email and without this footer and force push into pull request branch. I don’t remember if eclipse allow more than one email in account

**Comment by tbl0605** [comment]
> 
> 
> You are committer so sined off is not necessarry. Important is email you have in commit. So just amend with different email and without this footer and force push into pull request branch. I don’t remember if eclipse allow more than one email in account

Thank you for your advice Dawid, I changed the commit message. I first tried to completly remove the "Signed-off-by" line, and now I've added my "old" Signed-off-by to the commit message.
But the last check still fails, It doesn't seem to take care of my new commit message, any other advice?

**Comment by mlocati** [comment]
@tbl0605 simply run `git config user.email "your email address" and do a commit  (without the signed off stuff in the commit message)

**Comment by tbl0605** [comment]
> @tbl0605 simply run git config user.email "your email address" and do a commit (without the signed off stuff in the commit message)

Thanx for the advice ;) I won't do that to my poor machine, I need to keep my current configuration for all my other projects! ;)
I didn't know that amending a patch (and changing the Signed-off line) only affects the "Commiter" and keeps the original "Author" as-is. But that's logic off course....

I'll try command ```git commit --amend --author="..."``` it should work now :)
What a mess when using multiple email addresses! lol

**Comment by mlocati** [comment]
`git config user.email "your email address"` is repository-specific: your global git configuration won't be touched

**Comment by tbl0605** [comment]
> 
> 
> `git config user.email "your email address"` is repository-specific: your global git configuration won't be touched

Ok good to know, I'll do that for next patch then ;) It changes from gerrit, I had no such problems before, I have to be careful now!

**Comment by zulus** [comment]
> Ok good to know, I'll do that for next patch then ;) It changes from gerrit, I had no such problems before, I have to be careful now!

There is still a hope for https://bugs.eclipse.org/bugs/show_bug.cgi?id=461177 ;)

Hint: if during squash/merge you will change "Bug #59" to "Fix #59", GitHub will autoclose mentioned bug. Even "eclipse/" prefix isn't necessary :)

**Pull request merged**
