### PR TITLE
Replace WTP JSON editor by Generic Text Editor

### PR DESCRIPTION
**Pull request by zulus**

### CODE REVIEW

**Comment by zulus** [comment]
@tbl0605 I want merge this for M3 (I have to promote build tomorrow). Any concerns?

**Comment by tbl0605** [comment]
> 
> 
> @tbl0605 I want merge this for M3 (I have to promote build tomorrow). Any concerns?

No, that's actually a great idea. It would also be nice to remove the Javascript editor, since it's totally outdated (maybe you already did it in some builds, I haven't checked), There are a lot of javascript files that cannot be opened, even the compare editor doesn't work most of times...

**Comment by zulus** [comment]
I already did it. Just try 2020-06 M2. JSDT has been replaced by wildwebdeveloper. 

There is a hope that vue language server become part of it soon.

**Comment by zulus** [comment]
Only problem is nodejs. It have to be installed if you want code assist and validation. There is a plan to embed it, but probably in 2020-09

**Comment by tbl0605** [comment]
> I already did it. Just try 2020-06 M2. JSDT has been replaced by wildwebdeveloper.
Is it already on PDT master or did you a specific branch? I don't see what merge is related to the wildwebdeveloper integration.

**Pull request merged**
